object: orig/GXXE01/sys/main.dol
hash: ff9e752ead9914af0b363ae6c831a34ccce189d2
symbols: config/GXXE01/symbols.txt
splits: config/GXXE01/splits.txt
mw_comment_version: 10
ldscript_template: config/GXXE01/module/ldscript.lcf
